# -*- coding: utf-8 -*-
"""Language Translation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSeaqOxPY3SMEO6ulKYaz73Heu_Bg4nz
"""

from transformers import MarianMTModel,MarianTokenizer
import torch

def translation_model(target_lang):
  model_name=f"Helsinki-NLP/opus-mt-en-{target_lang}"
  tokenizer=MarianTokenizer.from_pretrained(model_name)
  model=MarianMTModel.from_pretrained(model_name)
  return tokenizer,model

def translate(texts,tokenizer,model):
  tokens=tokenizer(texts,return_tensors='pt',padding=True,truncation=True)
  translate=model.generate(**tokens)
  return [tokenizer.decode(t,skip_special_tokens=True) for t in translate]

target_lang="hi"
tokenizer,model=translation_model(target_lang)

input_texts=["I was the candle, she was the night."
             "I burned for her, she waited for the sun."]
translated_text=translate(input_texts,tokenizer,model)
for src,tgt in zip(input_texts,translated_text):
  print(f"{src} -> {tgt}")

